/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsWorkersCompRouteImport } from './routes/products.workers-comp'
import { Route as ProductsRvRouteImport } from './routes/products.rv'
import { Route as ProductsRentersRouteImport } from './routes/products.renters'
import { Route as ProductsMotorcycleRouteImport } from './routes/products.motorcycle'
import { Route as ProductsFloodRouteImport } from './routes/products.flood'
import { Route as InsuranceHomeRouteImport } from './routes/insurance.home'
import { Route as InsuranceBusinessRouteImport } from './routes/insurance.business'
import { Route as InsuranceAutoRouteImport } from './routes/insurance.auto'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsWorkersCompRoute = ProductsWorkersCompRouteImport.update({
  id: '/products/workers-comp',
  path: '/products/workers-comp',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRvRoute = ProductsRvRouteImport.update({
  id: '/products/rv',
  path: '/products/rv',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRentersRoute = ProductsRentersRouteImport.update({
  id: '/products/renters',
  path: '/products/renters',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsMotorcycleRoute = ProductsMotorcycleRouteImport.update({
  id: '/products/motorcycle',
  path: '/products/motorcycle',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsFloodRoute = ProductsFloodRouteImport.update({
  id: '/products/flood',
  path: '/products/flood',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceHomeRoute = InsuranceHomeRouteImport.update({
  id: '/insurance/home',
  path: '/insurance/home',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceBusinessRoute = InsuranceBusinessRouteImport.update({
  id: '/insurance/business',
  path: '/insurance/business',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceAutoRoute = InsuranceAutoRouteImport.update({
  id: '/insurance/auto',
  path: '/insurance/auto',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/insurance/auto': typeof InsuranceAutoRoute
  '/insurance/business': typeof InsuranceBusinessRoute
  '/insurance/home': typeof InsuranceHomeRoute
  '/products/flood': typeof ProductsFloodRoute
  '/products/motorcycle': typeof ProductsMotorcycleRoute
  '/products/renters': typeof ProductsRentersRoute
  '/products/rv': typeof ProductsRvRoute
  '/products/workers-comp': typeof ProductsWorkersCompRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/insurance/auto': typeof InsuranceAutoRoute
  '/insurance/business': typeof InsuranceBusinessRoute
  '/insurance/home': typeof InsuranceHomeRoute
  '/products/flood': typeof ProductsFloodRoute
  '/products/motorcycle': typeof ProductsMotorcycleRoute
  '/products/renters': typeof ProductsRentersRoute
  '/products/rv': typeof ProductsRvRoute
  '/products/workers-comp': typeof ProductsWorkersCompRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/services': typeof ServicesRoute
  '/insurance/auto': typeof InsuranceAutoRoute
  '/insurance/business': typeof InsuranceBusinessRoute
  '/insurance/home': typeof InsuranceHomeRoute
  '/products/flood': typeof ProductsFloodRoute
  '/products/motorcycle': typeof ProductsMotorcycleRoute
  '/products/renters': typeof ProductsRentersRoute
  '/products/rv': typeof ProductsRvRoute
  '/products/workers-comp': typeof ProductsWorkersCompRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/insurance/auto'
    | '/insurance/business'
    | '/insurance/home'
    | '/products/flood'
    | '/products/motorcycle'
    | '/products/renters'
    | '/products/rv'
    | '/products/workers-comp'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/insurance/auto'
    | '/insurance/business'
    | '/insurance/home'
    | '/products/flood'
    | '/products/motorcycle'
    | '/products/renters'
    | '/products/rv'
    | '/products/workers-comp'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/services'
    | '/insurance/auto'
    | '/insurance/business'
    | '/insurance/home'
    | '/products/flood'
    | '/products/motorcycle'
    | '/products/renters'
    | '/products/rv'
    | '/products/workers-comp'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ServicesRoute: typeof ServicesRoute
  InsuranceAutoRoute: typeof InsuranceAutoRoute
  InsuranceBusinessRoute: typeof InsuranceBusinessRoute
  InsuranceHomeRoute: typeof InsuranceHomeRoute
  ProductsFloodRoute: typeof ProductsFloodRoute
  ProductsMotorcycleRoute: typeof ProductsMotorcycleRoute
  ProductsRentersRoute: typeof ProductsRentersRoute
  ProductsRvRoute: typeof ProductsRvRoute
  ProductsWorkersCompRoute: typeof ProductsWorkersCompRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/workers-comp': {
      id: '/products/workers-comp'
      path: '/products/workers-comp'
      fullPath: '/products/workers-comp'
      preLoaderRoute: typeof ProductsWorkersCompRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/rv': {
      id: '/products/rv'
      path: '/products/rv'
      fullPath: '/products/rv'
      preLoaderRoute: typeof ProductsRvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/renters': {
      id: '/products/renters'
      path: '/products/renters'
      fullPath: '/products/renters'
      preLoaderRoute: typeof ProductsRentersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/motorcycle': {
      id: '/products/motorcycle'
      path: '/products/motorcycle'
      fullPath: '/products/motorcycle'
      preLoaderRoute: typeof ProductsMotorcycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/flood': {
      id: '/products/flood'
      path: '/products/flood'
      fullPath: '/products/flood'
      preLoaderRoute: typeof ProductsFloodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/home': {
      id: '/insurance/home'
      path: '/insurance/home'
      fullPath: '/insurance/home'
      preLoaderRoute: typeof InsuranceHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/business': {
      id: '/insurance/business'
      path: '/insurance/business'
      fullPath: '/insurance/business'
      preLoaderRoute: typeof InsuranceBusinessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance/auto': {
      id: '/insurance/auto'
      path: '/insurance/auto'
      fullPath: '/insurance/auto'
      preLoaderRoute: typeof InsuranceAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ServicesRoute: ServicesRoute,
  InsuranceAutoRoute: InsuranceAutoRoute,
  InsuranceBusinessRoute: InsuranceBusinessRoute,
  InsuranceHomeRoute: InsuranceHomeRoute,
  ProductsFloodRoute: ProductsFloodRoute,
  ProductsMotorcycleRoute: ProductsMotorcycleRoute,
  ProductsRentersRoute: ProductsRentersRoute,
  ProductsRvRoute: ProductsRvRoute,
  ProductsWorkersCompRoute: ProductsWorkersCompRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
